/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnergiaLoginRouteImport } from './routes/energia/login'
import { Route as AmbientalLoginRouteImport } from './routes/ambiental/login'
import { Route as EnergiaDashboardTarifarioRouteImport } from './routes/energia/dashboard/tarifario'
import { Route as EnergiaDashboardPanelRouteImport } from './routes/energia/dashboard/panel'
import { Route as EnergiaDashboardMonitoreoRouteImport } from './routes/energia/dashboard/monitoreo'
import { Route as EnergiaDashboardHomeRouteImport } from './routes/energia/dashboard/home'
import { Route as EnergiaDashboardDesbalanceRouteImport } from './routes/energia/dashboard/desbalance'
import { Route as EnergiaDashboardComparadorRouteImport } from './routes/energia/dashboard/comparador'
import { Route as EnergiaDashboardAlertasHistorialRouteImport } from './routes/energia/dashboard/alertas-historial'
import { Route as EnergiaDashboardAlertasRouteImport } from './routes/energia/dashboard/alertas'
import { Route as AmbientalDashboardRoomsRouteImport } from './routes/ambiental/dashboard/rooms'
import { Route as AmbientalDashboardMonitoreoRouteImport } from './routes/ambiental/dashboard/monitoreo'
import { Route as AmbientalDashboardAnalisisRouteImport } from './routes/ambiental/dashboard/analisis'
import { Route as AmbientalDashboardAlertasRouteImport } from './routes/ambiental/dashboard/alertas'
import { Route as EnergiaWaterDashboardPanelRouteImport } from './routes/energia/water/dashboard/panel'
import { Route as EnergiaWaterDashboardHomeRouteImport } from './routes/energia/water/dashboard/home'
import { Route as EnergiaWaterDashboardComparadorRouteImport } from './routes/energia/water/dashboard/comparador'
import { Route as EnergiaDashboardDesbalanceAlertasRouteImport } from './routes/energia/dashboard/desbalance/alertas'
import { Route as AmbientalDashboardAnalisisPicoshistoricosRouteImport } from './routes/ambiental/dashboard/analisis/picoshistoricos'
import { Route as AmbientalDashboardAnalisisIndicadoresRouteImport } from './routes/ambiental/dashboard/analisis/indicadores'
import { Route as AmbientalDashboardAnalisisEstadisticasRouteImport } from './routes/ambiental/dashboard/analisis/estadisticas'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaLoginRoute = EnergiaLoginRouteImport.update({
  id: '/energia/login',
  path: '/energia/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbientalLoginRoute = AmbientalLoginRouteImport.update({
  id: '/ambiental/login',
  path: '/ambiental/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaDashboardTarifarioRoute =
  EnergiaDashboardTarifarioRouteImport.update({
    id: '/energia/dashboard/tarifario',
    path: '/energia/dashboard/tarifario',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaDashboardPanelRoute = EnergiaDashboardPanelRouteImport.update({
  id: '/energia/dashboard/panel',
  path: '/energia/dashboard/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaDashboardMonitoreoRoute =
  EnergiaDashboardMonitoreoRouteImport.update({
    id: '/energia/dashboard/monitoreo',
    path: '/energia/dashboard/monitoreo',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaDashboardHomeRoute = EnergiaDashboardHomeRouteImport.update({
  id: '/energia/dashboard/home',
  path: '/energia/dashboard/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaDashboardDesbalanceRoute =
  EnergiaDashboardDesbalanceRouteImport.update({
    id: '/energia/dashboard/desbalance',
    path: '/energia/dashboard/desbalance',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaDashboardComparadorRoute =
  EnergiaDashboardComparadorRouteImport.update({
    id: '/energia/dashboard/comparador',
    path: '/energia/dashboard/comparador',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaDashboardAlertasHistorialRoute =
  EnergiaDashboardAlertasHistorialRouteImport.update({
    id: '/energia/dashboard/alertas-historial',
    path: '/energia/dashboard/alertas-historial',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaDashboardAlertasRoute = EnergiaDashboardAlertasRouteImport.update({
  id: '/energia/dashboard/alertas',
  path: '/energia/dashboard/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbientalDashboardRoomsRoute = AmbientalDashboardRoomsRouteImport.update({
  id: '/ambiental/dashboard/rooms',
  path: '/ambiental/dashboard/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbientalDashboardMonitoreoRoute =
  AmbientalDashboardMonitoreoRouteImport.update({
    id: '/ambiental/dashboard/monitoreo',
    path: '/ambiental/dashboard/monitoreo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AmbientalDashboardAnalisisRoute =
  AmbientalDashboardAnalisisRouteImport.update({
    id: '/ambiental/dashboard/analisis',
    path: '/ambiental/dashboard/analisis',
    getParentRoute: () => rootRouteImport,
  } as any)
const AmbientalDashboardAlertasRoute =
  AmbientalDashboardAlertasRouteImport.update({
    id: '/ambiental/dashboard/alertas',
    path: '/ambiental/dashboard/alertas',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaWaterDashboardPanelRoute =
  EnergiaWaterDashboardPanelRouteImport.update({
    id: '/energia/water/dashboard/panel',
    path: '/energia/water/dashboard/panel',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaWaterDashboardHomeRoute =
  EnergiaWaterDashboardHomeRouteImport.update({
    id: '/energia/water/dashboard/home',
    path: '/energia/water/dashboard/home',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaWaterDashboardComparadorRoute =
  EnergiaWaterDashboardComparadorRouteImport.update({
    id: '/energia/water/dashboard/comparador',
    path: '/energia/water/dashboard/comparador',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaDashboardDesbalanceAlertasRoute =
  EnergiaDashboardDesbalanceAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => EnergiaDashboardDesbalanceRoute,
  } as any)
const AmbientalDashboardAnalisisPicoshistoricosRoute =
  AmbientalDashboardAnalisisPicoshistoricosRouteImport.update({
    id: '/picoshistoricos',
    path: '/picoshistoricos',
    getParentRoute: () => AmbientalDashboardAnalisisRoute,
  } as any)
const AmbientalDashboardAnalisisIndicadoresRoute =
  AmbientalDashboardAnalisisIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AmbientalDashboardAnalisisRoute,
  } as any)
const AmbientalDashboardAnalisisEstadisticasRoute =
  AmbientalDashboardAnalisisEstadisticasRouteImport.update({
    id: '/estadisticas',
    path: '/estadisticas',
    getParentRoute: () => AmbientalDashboardAnalisisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/ambiental/login': typeof AmbientalLoginRoute
  '/energia/login': typeof EnergiaLoginRoute
  '/ambiental/dashboard/alertas': typeof AmbientalDashboardAlertasRoute
  '/ambiental/dashboard/analisis': typeof AmbientalDashboardAnalisisRouteWithChildren
  '/ambiental/dashboard/monitoreo': typeof AmbientalDashboardMonitoreoRoute
  '/ambiental/dashboard/rooms': typeof AmbientalDashboardRoomsRoute
  '/energia/dashboard/alertas': typeof EnergiaDashboardAlertasRoute
  '/energia/dashboard/alertas-historial': typeof EnergiaDashboardAlertasHistorialRoute
  '/energia/dashboard/comparador': typeof EnergiaDashboardComparadorRoute
  '/energia/dashboard/desbalance': typeof EnergiaDashboardDesbalanceRouteWithChildren
  '/energia/dashboard/home': typeof EnergiaDashboardHomeRoute
  '/energia/dashboard/monitoreo': typeof EnergiaDashboardMonitoreoRoute
  '/energia/dashboard/panel': typeof EnergiaDashboardPanelRoute
  '/energia/dashboard/tarifario': typeof EnergiaDashboardTarifarioRoute
  '/ambiental/dashboard/analisis/estadisticas': typeof AmbientalDashboardAnalisisEstadisticasRoute
  '/ambiental/dashboard/analisis/indicadores': typeof AmbientalDashboardAnalisisIndicadoresRoute
  '/ambiental/dashboard/analisis/picoshistoricos': typeof AmbientalDashboardAnalisisPicoshistoricosRoute
  '/energia/dashboard/desbalance/alertas': typeof EnergiaDashboardDesbalanceAlertasRoute
  '/energia/water/dashboard/comparador': typeof EnergiaWaterDashboardComparadorRoute
  '/energia/water/dashboard/home': typeof EnergiaWaterDashboardHomeRoute
  '/energia/water/dashboard/panel': typeof EnergiaWaterDashboardPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/ambiental/login': typeof AmbientalLoginRoute
  '/energia/login': typeof EnergiaLoginRoute
  '/ambiental/dashboard/alertas': typeof AmbientalDashboardAlertasRoute
  '/ambiental/dashboard/analisis': typeof AmbientalDashboardAnalisisRouteWithChildren
  '/ambiental/dashboard/monitoreo': typeof AmbientalDashboardMonitoreoRoute
  '/ambiental/dashboard/rooms': typeof AmbientalDashboardRoomsRoute
  '/energia/dashboard/alertas': typeof EnergiaDashboardAlertasRoute
  '/energia/dashboard/alertas-historial': typeof EnergiaDashboardAlertasHistorialRoute
  '/energia/dashboard/comparador': typeof EnergiaDashboardComparadorRoute
  '/energia/dashboard/desbalance': typeof EnergiaDashboardDesbalanceRouteWithChildren
  '/energia/dashboard/home': typeof EnergiaDashboardHomeRoute
  '/energia/dashboard/monitoreo': typeof EnergiaDashboardMonitoreoRoute
  '/energia/dashboard/panel': typeof EnergiaDashboardPanelRoute
  '/energia/dashboard/tarifario': typeof EnergiaDashboardTarifarioRoute
  '/ambiental/dashboard/analisis/estadisticas': typeof AmbientalDashboardAnalisisEstadisticasRoute
  '/ambiental/dashboard/analisis/indicadores': typeof AmbientalDashboardAnalisisIndicadoresRoute
  '/ambiental/dashboard/analisis/picoshistoricos': typeof AmbientalDashboardAnalisisPicoshistoricosRoute
  '/energia/dashboard/desbalance/alertas': typeof EnergiaDashboardDesbalanceAlertasRoute
  '/energia/water/dashboard/comparador': typeof EnergiaWaterDashboardComparadorRoute
  '/energia/water/dashboard/home': typeof EnergiaWaterDashboardHomeRoute
  '/energia/water/dashboard/panel': typeof EnergiaWaterDashboardPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/ambiental/login': typeof AmbientalLoginRoute
  '/energia/login': typeof EnergiaLoginRoute
  '/ambiental/dashboard/alertas': typeof AmbientalDashboardAlertasRoute
  '/ambiental/dashboard/analisis': typeof AmbientalDashboardAnalisisRouteWithChildren
  '/ambiental/dashboard/monitoreo': typeof AmbientalDashboardMonitoreoRoute
  '/ambiental/dashboard/rooms': typeof AmbientalDashboardRoomsRoute
  '/energia/dashboard/alertas': typeof EnergiaDashboardAlertasRoute
  '/energia/dashboard/alertas-historial': typeof EnergiaDashboardAlertasHistorialRoute
  '/energia/dashboard/comparador': typeof EnergiaDashboardComparadorRoute
  '/energia/dashboard/desbalance': typeof EnergiaDashboardDesbalanceRouteWithChildren
  '/energia/dashboard/home': typeof EnergiaDashboardHomeRoute
  '/energia/dashboard/monitoreo': typeof EnergiaDashboardMonitoreoRoute
  '/energia/dashboard/panel': typeof EnergiaDashboardPanelRoute
  '/energia/dashboard/tarifario': typeof EnergiaDashboardTarifarioRoute
  '/ambiental/dashboard/analisis/estadisticas': typeof AmbientalDashboardAnalisisEstadisticasRoute
  '/ambiental/dashboard/analisis/indicadores': typeof AmbientalDashboardAnalisisIndicadoresRoute
  '/ambiental/dashboard/analisis/picoshistoricos': typeof AmbientalDashboardAnalisisPicoshistoricosRoute
  '/energia/dashboard/desbalance/alertas': typeof EnergiaDashboardDesbalanceAlertasRoute
  '/energia/water/dashboard/comparador': typeof EnergiaWaterDashboardComparadorRoute
  '/energia/water/dashboard/home': typeof EnergiaWaterDashboardHomeRoute
  '/energia/water/dashboard/panel': typeof EnergiaWaterDashboardPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/ambiental/login'
    | '/energia/login'
    | '/ambiental/dashboard/alertas'
    | '/ambiental/dashboard/analisis'
    | '/ambiental/dashboard/monitoreo'
    | '/ambiental/dashboard/rooms'
    | '/energia/dashboard/alertas'
    | '/energia/dashboard/alertas-historial'
    | '/energia/dashboard/comparador'
    | '/energia/dashboard/desbalance'
    | '/energia/dashboard/home'
    | '/energia/dashboard/monitoreo'
    | '/energia/dashboard/panel'
    | '/energia/dashboard/tarifario'
    | '/ambiental/dashboard/analisis/estadisticas'
    | '/ambiental/dashboard/analisis/indicadores'
    | '/ambiental/dashboard/analisis/picoshistoricos'
    | '/energia/dashboard/desbalance/alertas'
    | '/energia/water/dashboard/comparador'
    | '/energia/water/dashboard/home'
    | '/energia/water/dashboard/panel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/ambiental/login'
    | '/energia/login'
    | '/ambiental/dashboard/alertas'
    | '/ambiental/dashboard/analisis'
    | '/ambiental/dashboard/monitoreo'
    | '/ambiental/dashboard/rooms'
    | '/energia/dashboard/alertas'
    | '/energia/dashboard/alertas-historial'
    | '/energia/dashboard/comparador'
    | '/energia/dashboard/desbalance'
    | '/energia/dashboard/home'
    | '/energia/dashboard/monitoreo'
    | '/energia/dashboard/panel'
    | '/energia/dashboard/tarifario'
    | '/ambiental/dashboard/analisis/estadisticas'
    | '/ambiental/dashboard/analisis/indicadores'
    | '/ambiental/dashboard/analisis/picoshistoricos'
    | '/energia/dashboard/desbalance/alertas'
    | '/energia/water/dashboard/comparador'
    | '/energia/water/dashboard/home'
    | '/energia/water/dashboard/panel'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/ambiental/login'
    | '/energia/login'
    | '/ambiental/dashboard/alertas'
    | '/ambiental/dashboard/analisis'
    | '/ambiental/dashboard/monitoreo'
    | '/ambiental/dashboard/rooms'
    | '/energia/dashboard/alertas'
    | '/energia/dashboard/alertas-historial'
    | '/energia/dashboard/comparador'
    | '/energia/dashboard/desbalance'
    | '/energia/dashboard/home'
    | '/energia/dashboard/monitoreo'
    | '/energia/dashboard/panel'
    | '/energia/dashboard/tarifario'
    | '/ambiental/dashboard/analisis/estadisticas'
    | '/ambiental/dashboard/analisis/indicadores'
    | '/ambiental/dashboard/analisis/picoshistoricos'
    | '/energia/dashboard/desbalance/alertas'
    | '/energia/water/dashboard/comparador'
    | '/energia/water/dashboard/home'
    | '/energia/water/dashboard/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  AmbientalLoginRoute: typeof AmbientalLoginRoute
  EnergiaLoginRoute: typeof EnergiaLoginRoute
  AmbientalDashboardAlertasRoute: typeof AmbientalDashboardAlertasRoute
  AmbientalDashboardAnalisisRoute: typeof AmbientalDashboardAnalisisRouteWithChildren
  AmbientalDashboardMonitoreoRoute: typeof AmbientalDashboardMonitoreoRoute
  AmbientalDashboardRoomsRoute: typeof AmbientalDashboardRoomsRoute
  EnergiaDashboardAlertasRoute: typeof EnergiaDashboardAlertasRoute
  EnergiaDashboardAlertasHistorialRoute: typeof EnergiaDashboardAlertasHistorialRoute
  EnergiaDashboardComparadorRoute: typeof EnergiaDashboardComparadorRoute
  EnergiaDashboardDesbalanceRoute: typeof EnergiaDashboardDesbalanceRouteWithChildren
  EnergiaDashboardHomeRoute: typeof EnergiaDashboardHomeRoute
  EnergiaDashboardMonitoreoRoute: typeof EnergiaDashboardMonitoreoRoute
  EnergiaDashboardPanelRoute: typeof EnergiaDashboardPanelRoute
  EnergiaDashboardTarifarioRoute: typeof EnergiaDashboardTarifarioRoute
  EnergiaWaterDashboardComparadorRoute: typeof EnergiaWaterDashboardComparadorRoute
  EnergiaWaterDashboardHomeRoute: typeof EnergiaWaterDashboardHomeRoute
  EnergiaWaterDashboardPanelRoute: typeof EnergiaWaterDashboardPanelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/login': {
      id: '/energia/login'
      path: '/energia/login'
      fullPath: '/energia/login'
      preLoaderRoute: typeof EnergiaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambiental/login': {
      id: '/ambiental/login'
      path: '/ambiental/login'
      fullPath: '/ambiental/login'
      preLoaderRoute: typeof AmbientalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/tarifario': {
      id: '/energia/dashboard/tarifario'
      path: '/energia/dashboard/tarifario'
      fullPath: '/energia/dashboard/tarifario'
      preLoaderRoute: typeof EnergiaDashboardTarifarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/panel': {
      id: '/energia/dashboard/panel'
      path: '/energia/dashboard/panel'
      fullPath: '/energia/dashboard/panel'
      preLoaderRoute: typeof EnergiaDashboardPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/monitoreo': {
      id: '/energia/dashboard/monitoreo'
      path: '/energia/dashboard/monitoreo'
      fullPath: '/energia/dashboard/monitoreo'
      preLoaderRoute: typeof EnergiaDashboardMonitoreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/home': {
      id: '/energia/dashboard/home'
      path: '/energia/dashboard/home'
      fullPath: '/energia/dashboard/home'
      preLoaderRoute: typeof EnergiaDashboardHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/desbalance': {
      id: '/energia/dashboard/desbalance'
      path: '/energia/dashboard/desbalance'
      fullPath: '/energia/dashboard/desbalance'
      preLoaderRoute: typeof EnergiaDashboardDesbalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/comparador': {
      id: '/energia/dashboard/comparador'
      path: '/energia/dashboard/comparador'
      fullPath: '/energia/dashboard/comparador'
      preLoaderRoute: typeof EnergiaDashboardComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/alertas-historial': {
      id: '/energia/dashboard/alertas-historial'
      path: '/energia/dashboard/alertas-historial'
      fullPath: '/energia/dashboard/alertas-historial'
      preLoaderRoute: typeof EnergiaDashboardAlertasHistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/alertas': {
      id: '/energia/dashboard/alertas'
      path: '/energia/dashboard/alertas'
      fullPath: '/energia/dashboard/alertas'
      preLoaderRoute: typeof EnergiaDashboardAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambiental/dashboard/rooms': {
      id: '/ambiental/dashboard/rooms'
      path: '/ambiental/dashboard/rooms'
      fullPath: '/ambiental/dashboard/rooms'
      preLoaderRoute: typeof AmbientalDashboardRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambiental/dashboard/monitoreo': {
      id: '/ambiental/dashboard/monitoreo'
      path: '/ambiental/dashboard/monitoreo'
      fullPath: '/ambiental/dashboard/monitoreo'
      preLoaderRoute: typeof AmbientalDashboardMonitoreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambiental/dashboard/analisis': {
      id: '/ambiental/dashboard/analisis'
      path: '/ambiental/dashboard/analisis'
      fullPath: '/ambiental/dashboard/analisis'
      preLoaderRoute: typeof AmbientalDashboardAnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambiental/dashboard/alertas': {
      id: '/ambiental/dashboard/alertas'
      path: '/ambiental/dashboard/alertas'
      fullPath: '/ambiental/dashboard/alertas'
      preLoaderRoute: typeof AmbientalDashboardAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/water/dashboard/panel': {
      id: '/energia/water/dashboard/panel'
      path: '/energia/water/dashboard/panel'
      fullPath: '/energia/water/dashboard/panel'
      preLoaderRoute: typeof EnergiaWaterDashboardPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/water/dashboard/home': {
      id: '/energia/water/dashboard/home'
      path: '/energia/water/dashboard/home'
      fullPath: '/energia/water/dashboard/home'
      preLoaderRoute: typeof EnergiaWaterDashboardHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/water/dashboard/comparador': {
      id: '/energia/water/dashboard/comparador'
      path: '/energia/water/dashboard/comparador'
      fullPath: '/energia/water/dashboard/comparador'
      preLoaderRoute: typeof EnergiaWaterDashboardComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia/dashboard/desbalance/alertas': {
      id: '/energia/dashboard/desbalance/alertas'
      path: '/alertas'
      fullPath: '/energia/dashboard/desbalance/alertas'
      preLoaderRoute: typeof EnergiaDashboardDesbalanceAlertasRouteImport
      parentRoute: typeof EnergiaDashboardDesbalanceRoute
    }
    '/ambiental/dashboard/analisis/picoshistoricos': {
      id: '/ambiental/dashboard/analisis/picoshistoricos'
      path: '/picoshistoricos'
      fullPath: '/ambiental/dashboard/analisis/picoshistoricos'
      preLoaderRoute: typeof AmbientalDashboardAnalisisPicoshistoricosRouteImport
      parentRoute: typeof AmbientalDashboardAnalisisRoute
    }
    '/ambiental/dashboard/analisis/indicadores': {
      id: '/ambiental/dashboard/analisis/indicadores'
      path: '/indicadores'
      fullPath: '/ambiental/dashboard/analisis/indicadores'
      preLoaderRoute: typeof AmbientalDashboardAnalisisIndicadoresRouteImport
      parentRoute: typeof AmbientalDashboardAnalisisRoute
    }
    '/ambiental/dashboard/analisis/estadisticas': {
      id: '/ambiental/dashboard/analisis/estadisticas'
      path: '/estadisticas'
      fullPath: '/ambiental/dashboard/analisis/estadisticas'
      preLoaderRoute: typeof AmbientalDashboardAnalisisEstadisticasRouteImport
      parentRoute: typeof AmbientalDashboardAnalisisRoute
    }
  }
}

interface AmbientalDashboardAnalisisRouteChildren {
  AmbientalDashboardAnalisisEstadisticasRoute: typeof AmbientalDashboardAnalisisEstadisticasRoute
  AmbientalDashboardAnalisisIndicadoresRoute: typeof AmbientalDashboardAnalisisIndicadoresRoute
  AmbientalDashboardAnalisisPicoshistoricosRoute: typeof AmbientalDashboardAnalisisPicoshistoricosRoute
}

const AmbientalDashboardAnalisisRouteChildren: AmbientalDashboardAnalisisRouteChildren =
  {
    AmbientalDashboardAnalisisEstadisticasRoute:
      AmbientalDashboardAnalisisEstadisticasRoute,
    AmbientalDashboardAnalisisIndicadoresRoute:
      AmbientalDashboardAnalisisIndicadoresRoute,
    AmbientalDashboardAnalisisPicoshistoricosRoute:
      AmbientalDashboardAnalisisPicoshistoricosRoute,
  }

const AmbientalDashboardAnalisisRouteWithChildren =
  AmbientalDashboardAnalisisRoute._addFileChildren(
    AmbientalDashboardAnalisisRouteChildren,
  )

interface EnergiaDashboardDesbalanceRouteChildren {
  EnergiaDashboardDesbalanceAlertasRoute: typeof EnergiaDashboardDesbalanceAlertasRoute
}

const EnergiaDashboardDesbalanceRouteChildren: EnergiaDashboardDesbalanceRouteChildren =
  {
    EnergiaDashboardDesbalanceAlertasRoute:
      EnergiaDashboardDesbalanceAlertasRoute,
  }

const EnergiaDashboardDesbalanceRouteWithChildren =
  EnergiaDashboardDesbalanceRoute._addFileChildren(
    EnergiaDashboardDesbalanceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  AmbientalLoginRoute: AmbientalLoginRoute,
  EnergiaLoginRoute: EnergiaLoginRoute,
  AmbientalDashboardAlertasRoute: AmbientalDashboardAlertasRoute,
  AmbientalDashboardAnalisisRoute: AmbientalDashboardAnalisisRouteWithChildren,
  AmbientalDashboardMonitoreoRoute: AmbientalDashboardMonitoreoRoute,
  AmbientalDashboardRoomsRoute: AmbientalDashboardRoomsRoute,
  EnergiaDashboardAlertasRoute: EnergiaDashboardAlertasRoute,
  EnergiaDashboardAlertasHistorialRoute: EnergiaDashboardAlertasHistorialRoute,
  EnergiaDashboardComparadorRoute: EnergiaDashboardComparadorRoute,
  EnergiaDashboardDesbalanceRoute: EnergiaDashboardDesbalanceRouteWithChildren,
  EnergiaDashboardHomeRoute: EnergiaDashboardHomeRoute,
  EnergiaDashboardMonitoreoRoute: EnergiaDashboardMonitoreoRoute,
  EnergiaDashboardPanelRoute: EnergiaDashboardPanelRoute,
  EnergiaDashboardTarifarioRoute: EnergiaDashboardTarifarioRoute,
  EnergiaWaterDashboardComparadorRoute: EnergiaWaterDashboardComparadorRoute,
  EnergiaWaterDashboardHomeRoute: EnergiaWaterDashboardHomeRoute,
  EnergiaWaterDashboardPanelRoute: EnergiaWaterDashboardPanelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
